<a href="https://colab.research.google.com/github/Mayk17/ai_foundation/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [4]:
import numpy as np

arr = np.array([1, 3, 5, 6])
print('numpy_array:', arr)
arr.shape

numpy_array: [1 3 5 6]


(4,)

In [7]:
arr2 = np.array([[1, 4, 5, 6], [3, 5, 7, 5]])
print("numpy_array:", arr2)
arr2.shape

numpy_array: [[1 4 5 6]
 [3 5 7 5]]


(2, 4)

In [ ]:
#dtype
a = np.array([1, 2, 4])
print(a.dtype)

In [2]:
#reshape()
import numpy as np
a= np.array([1, 2, 5, 6, 9, 3])
b = a.reshape(2, 3)
print("shaped_array:", b)

shaped_array: [[1 2 5]
 [6 9 3]]


In [3]:
#astype
a = np.array([1, 2, 4,])
b = a.astype(float)
print("float:", b)

float: [1. 2. 4.]


In [4]:
# np.zeos(), np.ones() => dummy data # hammasi matrisa hosil qilib berdi.
z = np.zeros((2, 4))
o = np.ones((2, 4))

print("zeros:", z)
print("ones:", o)

zeros: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
#ndim
a = np.array([[1, 2], [4, 6]])
print("ndim:", a.ndim)

ndim: 2


In [7]:
#arange()
a = np.arange(1, 7)
print("arange:", a)

arange: [1 2 3 4 5 6]


In [2]:
# sum() mean() mix() max()
import numpy as np
a = np.array([1, 2, 3, 4])

print("sum:", a.sum())
print("mean:", a.mean())
print("max:", a.max())
print("min:", a.min())

sum: 10
mean: 2.5
max: 4
min: 1


In [3]:
# flatten()

a = np.array([[11, 2], [4, 6]])
print("flatten:", a.flatten())

flatten: [11  2  4  6]


In [5]:
# T (Transpose)
a = np.array([[1, 4], [5, 7]])
print("transpose:", a.T)

transpose: [[1 5]
 [4 7]]


In [6]:
#dot() @
a = np.array([[1, 2], [7, 0]])
b = np.array([[2, 3], [5, 1]])
print("dot/ multiplication:", a.dot(b))

dot/ multiplication: [[12  5]
 [14 21]]


In [7]:
#random.rand()
a = np.random.rand(2, 4) # => 0.0 and 1.0 / 0.0 included/ 1.0 excluded
print("random rand:", a)

random rand: [[0.87282595 0.37396555 0.04450373 0.22533277]
 [0.14884154 0.65731231 0.6696435  0.36771173]]
