<a href="https://colab.research.google.com/github/Mayk17/ai_foundation/blob/main/students_performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
!pip install pandas numpy

In [10]:
import pandas as pd
import numpy as np

In [13]:
df = pd.read_csv("StudentsPerformance.csv")
print("Dataset shape(row, columns):", df.shape) # qancha qator va qancha ustun borligin bilish uchun kerak
print("Column name:", df.columns.tolist()) # ustundagi labalellar nomi

print("Frist 5 rows of the dataset:")
print(df.head()) # 5ta ustunni olib beradi

print("Summary statistics:")
print(df.describe()) # stastitik malumot

print("data types and null info:")
print(df.info()) #


Dataset shape(row, columns): (1000, 8)
Column name: ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'math score', 'reading score', 'writing score']
Frist 5 rows of the dataset:
   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4   

In [14]:
print("Average score by subject:")
df[["Age", "Absences", "StudyTimeWeekly"]].mean()

Average score by subject:


KeyError: "None of [Index(['Age', 'Absences', 'StudyTimeWeekly'], dtype='object')] are in the [columns]"

In [ ]:
print("Maximum score by students:")
df[["Age", "Absences", "StudyTimeWeekly"]].max()

Maximum score by students:


,0
Age,18.000000
Absences,29.000000
StudyTimeWeekly,19.978094


In [ ]:
print("Minimu score by students:")
df[["Age", "Absences", "StudyTimeWeekly"]].min()

Minimu score by students:


,0
Age,15.000000
Absences,0.000000
StudyTimeWeekly,0.001057


In [ ]:
print("Correlation")
df[["Age", "Absences", "StudyTimeWeekly"]].corr()

Correlation


,Age,Absences,StudyTimeWeekly
Age,1.000000,-0.011511,-0.006800
Absences,-0.011511,1.000000,0.009326
StudyTimeWeekly,-0.006800,0.009326,1.000000


In [15]:
test_prep_groupby = df.groupby('test preparation course')[["math score", "reading score", "writing score"]].mean()
print("student score by test preparation course:")
print(test_prep_groupby)

# Gender-based  average
gender_avg = df.groupby('gender')[["math score", "reading score", "writing score"]].mean()
print("student score by gender:")
print(gender_avg)

#who passed vs failed

pass_rate = df["passed"].value_counts(normalize=True) * 100
print("Pass rate:\n", pass_rate)

student score by test preparation course:
                         math score  reading score  writing score
test preparation course                                          
completed                 69.695531      73.893855      74.418994
none                      64.077882      66.534268      64.504673
student score by gender:
        math score  reading score  writing score
gender                                          
female   63.633205      72.608108      72.467181
male     68.728216      65.473029      63.311203


KeyError: 'passed'

In [16]:
print(df.columns)


Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')


In [18]:
#Convert scores to Numpy array
scores = df[["math score", "reading score", "writing score"]].values


# Mean, Std Devition
print("Numpy Mean:", np.mean(scores, axis=0))
print("Numpy Std Deviation:", np.std(scores, axis=0))
#Z-score (normalize)
z_scores = (scores - np.mean(scores, axis=0)) / np.std(scores, axis=0)
print("Z-scores:\n", z_scores)

# Average 0
# Negative -
# Positive +


Numpy Mean: [66.089 69.169 68.054]
Numpy Std Deviation: [15.15549666 14.59289002 15.18805728]
Z-scores:
 [[ 0.39002351  0.19399858  0.39149181]
 [ 0.19207553  1.42747598  1.31326868]
 [ 1.57771141  1.77010859  1.64247471]
 ...
 [-0.46775108  0.12547206 -0.20107904]
 [ 0.12609287  0.60515772  0.58901542]
 [ 0.71993682  1.15336989  1.18158627]]


In [29]:
# How many students scored above 90 average?
top_scorers = df[df['math score'] >= 90]
print("Top Scorers above 90:", len(top_scorers))

#How many failed ?
failed_students = df[df['math score'] <=60]
print("Failed Students:", len(failed_students))

Top Scorers above 90: 58
Failed Students: 339
